/*
 * generated by Xtext
 */
package electrickery.dssdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DssDslUiModule extends electrickery.dssdsl.ui.AbstractDssDslUiModule {
	public DssDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
