package com.ncond.dss.plot;

public enum PlotType {
	AUTO_ADD_LOG_PLOT,
	CIRCUIT_PLOT,
	GENERAL_DATA_PLOT,
	GENERAL_CIRCUIT_PLOT,
	MONITOR_PLOT,
	DAISY_PLOT,
	METER_ZONES,
	LOAD_SHAPE,
	TSHAPE,
	PRICE_SHAPE,
	PROFILE
}