/*
* generated by Xtext
*/
package electrickery.dssdsl.ui.contentassist;

import electrickery.dssdsl.ui.contentassist.AbstractDssDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DssDslProposalProvider extends AbstractDssDslProposalProvider {

}
