/*
 * generated by Xtext
 */
package electrickery.dssdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DssDslRuntimeModule extends electrickery.dssdsl.AbstractDssDslRuntimeModule {

}
