
/*
 * generated by Xtext
 */
 
package electrickery.dssdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class DssDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return electrickery.dssdsl.ui.internal.DssDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return electrickery.dssdsl.ui.internal.DssDslActivator.getInstance().getInjector("electrickery.dssdsl.DssDsl");
	}
	
}
