/*
* generated by Xtext
*/
package electrickery.dssdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DssDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
